#include <Arduino.h>

// This file is generated by `node ./src/password-cross-check.js > ./src/passwords.h`

const char db1_00_0[] PROGMEM = "ACRE";
const char db1_00_1[] PROGMEM = "LOREM";
const char db1_00_2[] PROGMEM = "IPSUM";
const char db1_00_3[] PROGMEM = "DOLAM";
const char db1_00_4[] PROGMEM = "SITAM";
const char db1_01_0[] PROGMEM = "ALSO";
const char db1_01_1[] PROGMEM = "ETJCN";
const char db1_01_2[] PROGMEM = "CONZE";
const char db1_01_3[] PROGMEM = "CTEUR";
const char db1_01_4[] PROGMEM = "ADIPS";
const char db1_02_0[] PROGMEM = "CAMP";
const char db1_02_1[] PROGMEM = "LPDSO";
const char db1_02_2[] PROGMEM = "UZQRH";
const char db1_02_3[] PROGMEM = "OQPLK";
const char db1_02_4[] PROGMEM = "TAJCH";
const char db1_03_0[] PROGMEM = "CENT";
const char db1_03_1[] PROGMEM = "LPBSO";
const char db1_03_2[] PROGMEM = "UZQRH";
const char db1_03_3[] PROGMEM = "OQPLK";
const char db1_03_4[] PROGMEM = "FADCH";
const char db1_04_0[] PROGMEM = "CHIP";
const char db1_04_1[] PROGMEM = "NAMES";
const char db1_04_2[] PROGMEM = "AEOUV";
const char db1_04_3[] PROGMEM = "BWSOK";
const char db1_04_4[] PROGMEM = "ERSTF";
const char db1_05_0[] PROGMEM = "DENT";
const char db1_05_1[] PROGMEM = "AEHWN";
const char db1_05_2[] PROGMEM = "ZABLV";
const char db1_05_3[] PROGMEM = "JPMIC";
const char db1_05_4[] PROGMEM = "AHLVQ";
const char db1_06_0[] PROGMEM = "DOME";
const char db1_06_1[] PROGMEM = "RUMAN";
const char db1_06_2[] PROGMEM = "ACFHU";
const char db1_06_3[] PROGMEM = "NIJSK";
const char db1_06_4[] PROGMEM = "FLSCD";
const char db1_07_0[] PROGMEM = "FIRE";
const char db1_07_1[] PROGMEM = "TIHGJ";
const char db1_07_2[] PROGMEM = "GAPUD";
const char db1_07_3[] PROGMEM = "VEYCL";
const char db1_07_4[] PROGMEM = "PTKSN";
const char db1_08_0[] PROGMEM = "ICED";
const char db1_08_1[] PROGMEM = "NULAM";
const char db1_08_2[] PROGMEM = "EOLAB";
const char db1_08_3[] PROGMEM = "OPISN";
const char db1_08_4[] PROGMEM = "ISETA";
const char db1_09_0[] PROGMEM = "HIGH";
const char db1_09_1[] PROGMEM = "STWAU";
const char db1_09_2[] PROGMEM = "DHOFL";
const char db1_09_3[] PROGMEM = "FHIDK";
const char db1_09_4[] PROGMEM = "OEBAN";
const char db1_10_0[] PROGMEM = "HEAR";
const char db1_10_1[] PROGMEM = "YNAFJ";
const char db1_10_2[] PROGMEM = "KRONZ";
const char db1_10_3[] PROGMEM = "CLIRU";
const char db1_10_4[] PROGMEM = "HMAET";
const char db1_11_0[] PROGMEM = "HELP";
const char db1_11_1[] PROGMEM = "FNIRT";
const char db1_11_2[] PROGMEM = "OSJDW";
const char db1_11_3[] PROGMEM = "HKMER";
const char db1_11_4[] PROGMEM = "UWEBT";
const char db1_12_0[] PROGMEM = "KEPT";
const char db1_12_1[] PROGMEM = "ERMCI";
const char db1_12_2[] PROGMEM = "LUYAT";
const char db1_12_3[] PROGMEM = "BECAF";
const char db1_12_4[] PROGMEM = "SHEMW";
const char db1_13_0[] PROGMEM = "KNEW";
const char db1_13_1[] PROGMEM = "ELPTW";
const char db1_13_2[] PROGMEM = "CULPA";
const char db1_13_3[] PROGMEM = "MOLNT";
const char db1_13_4[] PROGMEM = "LAPOR";
const char db1_14_0[] PROGMEM = "KNOB";
const char db1_14_1[] PROGMEM = "OFQSD";
const char db1_14_2[] PROGMEM = "RIPED";
const char db1_14_3[] PROGMEM = "FINTS";
const char db1_14_4[] PROGMEM = "ZLURH";
const char db1_15_0[] PROGMEM = "LAMB";
const char db1_15_1[] PROGMEM = "KODER";
const char db1_15_2[] PROGMEM = "TUVWB";
const char db1_15_3[] PROGMEM = "SNAKY";
const char db1_15_4[] PROGMEM = "CDEFG";
const char db1_16_0[] PROGMEM = "LEAP";
const char db1_16_1[] PROGMEM = "MOREP";
const char db1_16_2[] PROGMEM = "YTOKV";
const char db1_16_3[] PROGMEM = "BIREN";
const char db1_16_4[] PROGMEM = "CODAN";
const char db1_17_0[] PROGMEM = "MELT";
const char db1_17_1[] PROGMEM = "SNACK";
const char db1_17_2[] PROGMEM = "LUNCH";
const char db1_17_3[] PROGMEM = "BFAST";
const char db1_17_4[] PROGMEM = "DINER";
const char db1_18_0[] PROGMEM = "MINE";
const char db1_18_1[] PROGMEM = "SLXOU";
const char db1_18_2[] PROGMEM = "UARYC";
const char db1_18_3[] PROGMEM = "AMPIJ";
const char db1_18_4[] PROGMEM = "LPRAD";
const char db1_19_0[] PROGMEM = "MINT";
const char db1_19_1[] PROGMEM = "GOCUJ";
const char db1_19_2[] PROGMEM = "ALDBO";
const char db1_19_3[] PROGMEM = "ERLVI";
const char db1_19_4[] PROGMEM = "QBFSL";
const char db1_20_0[] PROGMEM = "NEXT";
const char db1_20_1[] PROGMEM = "TOADB";
const char db1_20_2[] PROGMEM = "IPSAK";
const char db1_20_3[] PROGMEM = "JVLCR";
const char db1_20_4[] PROGMEM = "BURKY";
const char db1_21_0[] PROGMEM = "OAKS";
const char db1_21_1[] PROGMEM = "CYABP";
const char db1_21_2[] PROGMEM = "SUEKQ";
const char db1_21_3[] PROGMEM = "JBIMC";
const char db1_21_4[] PROGMEM = "ZCLGE";
const char db1_22_0[] PROGMEM = "OPEN";
const char db1_22_1[] PROGMEM = "TEDPI";
const char db1_22_2[] PROGMEM = "BAWIJ";
const char db1_22_3[] PROGMEM = "SCRIL";
const char db1_22_4[] PROGMEM = "UPBKF";
const char db1_23_0[] PROGMEM = "PALM";
const char db1_23_1[] PROGMEM = "TRIWO";
const char db1_23_2[] PROGMEM = "ECUWF";
const char db1_23_3[] PROGMEM = "JBDYI";
const char db1_23_4[] PROGMEM = "KUFPS";
const char db1_24_0[] PROGMEM = "PASS";
const char db1_24_1[] PROGMEM = "JIMBW";
const char db1_24_2[] PROGMEM = "OIKWD";
const char db1_24_3[] PROGMEM = "NLOTE";
const char db1_24_4[] PROGMEM = "ZKOPY";
const char db1_25_0[] PROGMEM = "PREY";
const char db1_25_1[] PROGMEM = "SHOEL";
const char db1_25_2[] PROGMEM = "HXFBI";
const char db1_25_3[] PROGMEM = "AUOPT";
const char db1_25_4[] PROGMEM = "VFNWJ";
const char db1_26_0[] PROGMEM = "QUIZ";
const char db1_26_1[] PROGMEM = "PIYUM";
const char db1_26_2[] PROGMEM = "ZAMIL";
const char db1_26_3[] PROGMEM = "GKUFS";
const char db1_26_4[] PROGMEM = "FCLWG";
const char db1_27_0[] PROGMEM = "RAMP";
const char db1_27_1[] PROGMEM = "LEHUF";
const char db1_27_2[] PROGMEM = "HIYGR";
const char db1_27_3[] PROGMEM = "LNOCV";
const char db1_27_4[] PROGMEM = "IDCOA";
const char db1_28_0[] PROGMEM = "TENT";
const char db1_28_1[] PROGMEM = "BIGXL";
const char db1_28_2[] PROGMEM = "TINYO";
const char db1_28_3[] PROGMEM = "AMCLB";
const char db1_28_4[] PROGMEM = "DINOB";
const char db1_29_0[] PROGMEM = "XRAY";
const char db1_29_1[] PROGMEM = "YZQCB";
const char db1_29_2[] PROGMEM = "OHSAK";
const char db1_29_3[] PROGMEM = "UNDEC";
const char db1_29_4[] PROGMEM = "ABOKE";

PGM_P const db1[] PROGMEM = {
  db1_00_0, db1_00_1, db1_00_2, db1_00_3, db1_00_4,
  db1_01_0, db1_01_1, db1_01_2, db1_01_3, db1_01_4,
  db1_02_0, db1_02_1, db1_02_2, db1_02_3, db1_02_4,
  db1_03_0, db1_03_1, db1_03_2, db1_03_3, db1_03_4,
  db1_04_0, db1_04_1, db1_04_2, db1_04_3, db1_04_4,
  db1_05_0, db1_05_1, db1_05_2, db1_05_3, db1_05_4,
  db1_06_0, db1_06_1, db1_06_2, db1_06_3, db1_06_4,
  db1_07_0, db1_07_1, db1_07_2, db1_07_3, db1_07_4,
  db1_08_0, db1_08_1, db1_08_2, db1_08_3, db1_08_4,
  db1_09_0, db1_09_1, db1_09_2, db1_09_3, db1_09_4,
  db1_10_0, db1_10_1, db1_10_2, db1_10_3, db1_10_4,
  db1_11_0, db1_11_1, db1_11_2, db1_11_3, db1_11_4,
  db1_12_0, db1_12_1, db1_12_2, db1_12_3, db1_12_4,
  db1_13_0, db1_13_1, db1_13_2, db1_13_3, db1_13_4,
  db1_14_0, db1_14_1, db1_14_2, db1_14_3, db1_14_4,
  db1_15_0, db1_15_1, db1_15_2, db1_15_3, db1_15_4,
  db1_16_0, db1_16_1, db1_16_2, db1_16_3, db1_16_4,
  db1_17_0, db1_17_1, db1_17_2, db1_17_3, db1_17_4,
  db1_18_0, db1_18_1, db1_18_2, db1_18_3, db1_18_4,
  db1_19_0, db1_19_1, db1_19_2, db1_19_3, db1_19_4,
  db1_20_0, db1_20_1, db1_20_2, db1_20_3, db1_20_4,
  db1_21_0, db1_21_1, db1_21_2, db1_21_3, db1_21_4,
  db1_22_0, db1_22_1, db1_22_2, db1_22_3, db1_22_4,
  db1_23_0, db1_23_1, db1_23_2, db1_23_3, db1_23_4,
  db1_24_0, db1_24_1, db1_24_2, db1_24_3, db1_24_4,
  db1_25_0, db1_25_1, db1_25_2, db1_25_3, db1_25_4,
  db1_26_0, db1_26_1, db1_26_2, db1_26_3, db1_26_4,
  db1_27_0, db1_27_1, db1_27_2, db1_27_3, db1_27_4,
  db1_28_0, db1_28_1, db1_28_2, db1_28_3, db1_28_4,
  db1_29_0, db1_29_1, db1_29_2, db1_29_3, db1_29_4,
};

const char db2_00_0[] PROGMEM = "BACK";
const char db2_00_1[] PROGMEM = "PJMET";
const char db2_00_2[] PROGMEM = "ELYHR";
const char db2_00_3[] PROGMEM = "SNPIB";
const char db2_00_4[] PROGMEM = "GCDWV";
const char db2_01_0[] PROGMEM = "BOMB";
const char db2_01_1[] PROGMEM = "DLKFA";
const char db2_01_2[] PROGMEM = "ZGICH";
const char db2_01_3[] PROGMEM = "LADNS";
const char db2_01_4[] PROGMEM = "FRPTJ";
const char db2_02_0[] PROGMEM = "CUBE";
const char db2_02_1[] PROGMEM = "INGEL";
const char db2_02_2[] PROGMEM = "ITSED";
const char db2_02_3[] PROGMEM = "DOEIU";
const char db2_02_4[] PROGMEM = "MAGNL";
const char db2_03_0[] PROGMEM = "EZRA";
const char db2_03_1[] PROGMEM = "SDKUA";
const char db2_03_2[] PROGMEM = "WAJOK";
const char db2_03_3[] PROGMEM = "TSMEX";
const char db2_03_4[] PROGMEM = "YFPMB";
const char db2_04_0[] PROGMEM = "FISH";
const char db2_04_1[] PROGMEM = "LIQUA";
const char db2_04_2[] PROGMEM = "UTEND";
const char db2_04_3[] PROGMEM = "MADIN";
const char db2_04_4[] PROGMEM = "VENIA";
const char db2_05_0[] PROGMEM = "FEET";
const char db2_05_1[] PROGMEM = "MQUIS";
const char db2_05_2[] PROGMEM = "NOSTR";
const char db2_05_3[] PROGMEM = "UDSXR";
const char db2_05_4[] PROGMEM = "CIPAO";
const char db2_06_0[] PROGMEM = "GAME";
const char db2_06_1[] PROGMEM = "JOQDT";
const char db2_06_2[] PROGMEM = "EUSPR";
const char db2_06_3[] PROGMEM = "NBSPX";
const char db2_06_4[] PROGMEM = "ABCFT";
const char db2_07_0[] PROGMEM = "GOLF";
const char db2_07_1[] PROGMEM = "PIELX";
const char db2_07_2[] PROGMEM = "GCHIR";
const char db2_07_3[] PROGMEM = "BMAID";
const char db2_07_4[] PROGMEM = "WATER";
const char db2_08_0[] PROGMEM = "GONE";
const char db2_08_1[] PROGMEM = "HSYOK";
const char db2_08_2[] PROGMEM = "EMTZS";
const char db2_08_3[] PROGMEM = "BIWPG";
const char db2_08_4[] PROGMEM = "ASCIT";
const char db2_09_0[] PROGMEM = "HALO";
const char db2_09_1[] PROGMEM = "IQUPE";
const char db2_09_2[] PROGMEM = "EXRCM";
const char db2_09_3[] PROGMEM = "ODCNS";
const char db2_09_4[] PROGMEM = "UATDS";
const char db2_10_0[] PROGMEM = "HERE";
const char db2_10_1[] PROGMEM = "DUNSA";
const char db2_10_2[] PROGMEM = "UTARD";
const char db2_10_3[] PROGMEM = "OLAND";
const char db2_10_4[] PROGMEM = "LPKHI";
const char db2_11_0[] PROGMEM = "JUMP";
const char db2_11_1[] PROGMEM = "DIREC";
const char db2_11_2[] PROGMEM = "INVOL";
const char db2_11_3[] PROGMEM = "UPTAE";
const char db2_11_4[] PROGMEM = "VELIT";
const char db2_12_0[] PROGMEM = "LAMP";
const char db2_12_1[] PROGMEM = "BZTNO";
const char db2_12_2[] PROGMEM = "SURKW";
const char db2_12_3[] PROGMEM = "GOBSC";
const char db2_12_4[] PROGMEM = "RFTSE";
const char db2_13_0[] PROGMEM = "NAIL";
const char db2_13_1[] PROGMEM = "STMLO";
const char db2_13_2[] PROGMEM = "WPEDZ";
const char db2_13_3[] PROGMEM = "UXFDJ";
const char db2_13_4[] PROGMEM = "MWIFX";
const char db2_14_0[] PROGMEM = "NONE";
const char db2_14_1[] PROGMEM = "QUFWB";
const char db2_14_2[] PROGMEM = "RTANB";
const char db2_14_3[] PROGMEM = "BGRXD";
const char db2_14_4[] PROGMEM = "SPNIF";
const char db2_15_0[] PROGMEM = "NOPE";
const char db2_15_1[] PROGMEM = "JRPHE";
const char db2_15_2[] PROGMEM = "AXRFL";
const char db2_15_3[] PROGMEM = "AYTRM";
const char db2_15_4[] PROGMEM = "PUJMF";
const char db2_16_0[] PROGMEM = "PAIL";
const char db2_16_1[] PROGMEM = "EBIRJ";
const char db2_16_2[] PROGMEM = "NPOSV";
const char db2_16_3[] PROGMEM = "UYLSV";
const char db2_16_4[] PROGMEM = "XFBKI";
const char db2_17_0[] PROGMEM = "PATH";
const char db2_17_1[] PROGMEM = "HRJSX";
const char db2_17_2[] PROGMEM = "QDIGO";
const char db2_17_3[] PROGMEM = "SCRJG";
const char db2_17_4[] PROGMEM = "ZLUVJ";
const char db2_18_0[] PROGMEM = "POND";
const char db2_18_1[] PROGMEM = "EYTHJ";
const char db2_18_2[] PROGMEM = "FWLJE";
const char db2_18_3[] PROGMEM = "CBQRV";
const char db2_18_4[] PROGMEM = "ZXVGP";
const char db2_19_0[] PROGMEM = "PRAY";
const char db2_19_1[] PROGMEM = "BUJDH";
const char db2_19_2[] PROGMEM = "TMUWY";
const char db2_19_3[] PROGMEM = "FWHCE";
const char db2_19_4[] PROGMEM = "BVKCL";
const char db2_20_0[] PROGMEM = "RACE";
const char db2_20_1[] PROGMEM = "XNDFG";
const char db2_20_2[] PROGMEM = "QUOSM";
const char db2_20_3[] PROGMEM = "DUFGZ";
const char db2_20_4[] PROGMEM = "WZOFU";
const char db2_21_0[] PROGMEM = "RAKE";
const char db2_21_1[] PROGMEM = "NVXUA";
const char db2_21_2[] PROGMEM = "ZSQFP";
const char db2_21_3[] PROGMEM = "SXDYJ";
const char db2_21_4[] PROGMEM = "ILBGY";
const char db2_22_0[] PROGMEM = "SEND";
const char db2_22_1[] PROGMEM = "LGOAT";
const char db2_22_2[] PROGMEM = "DOIBQ";
const char db2_22_3[] PROGMEM = "UVRAY";
const char db2_22_4[] PROGMEM = "BIPMO";
const char db2_23_0[] PROGMEM = "SHIP";
const char db2_23_1[] PROGMEM = "FOUNT";
const char db2_23_2[] PROGMEM = "XLEKG";
const char db2_23_3[] PROGMEM = "BLAMP";
const char db2_23_4[] PROGMEM = "SHADE";
const char db2_24_0[] PROGMEM = "SIDE";
const char db2_24_1[] PROGMEM = "MITEY";
const char db2_24_2[] PROGMEM = "CWONG";
const char db2_24_3[] PROGMEM = "WIRTY";
const char db2_24_4[] PROGMEM = "LOQPS";
const char db2_25_0[] PROGMEM = "TICK";
const char db2_25_1[] PROGMEM = "FQHAL";
const char db2_25_2[] PROGMEM = "AQKXL";
const char db2_25_3[] PROGMEM = "XOYID";
const char db2_25_4[] PROGMEM = "GEUZT";
const char db2_26_0[] PROGMEM = "TIME";
const char db2_26_1[] PROGMEM = "ILMUN";
const char db2_26_2[] PROGMEM = "VOCZU";
const char db2_26_3[] PROGMEM = "KDVER";
const char db2_26_4[] PROGMEM = "RCQZO";
const char db2_27_0[] PROGMEM = "TOCK";
const char db2_27_1[] PROGMEM = "SLJGF";
const char db2_27_2[] PROGMEM = "URPVB";
const char db2_27_3[] PROGMEM = "WDXPS";
const char db2_27_4[] PROGMEM = "VJTNW";
const char db2_28_0[] PROGMEM = "WALK";
const char db2_28_1[] PROGMEM = "OFKGT";
const char db2_28_2[] PROGMEM = "SPGHK";
const char db2_28_3[] PROGMEM = "MBNUZ";
const char db2_28_4[] PROGMEM = "DIYLP";
const char db2_29_0[] PROGMEM = "WINK";
const char db2_29_1[] PROGMEM = "CIGPF";
const char db2_29_2[] PROGMEM = "AXRPE";
const char db2_29_3[] PROGMEM = "BADWH";
const char db2_29_4[] PROGMEM = "QHDIP";

PGM_P const db2[] PROGMEM = {
  db2_00_0, db2_00_1, db2_00_2, db2_00_3, db2_00_4,
  db2_01_0, db2_01_1, db2_01_2, db2_01_3, db2_01_4,
  db2_02_0, db2_02_1, db2_02_2, db2_02_3, db2_02_4,
  db2_03_0, db2_03_1, db2_03_2, db2_03_3, db2_03_4,
  db2_04_0, db2_04_1, db2_04_2, db2_04_3, db2_04_4,
  db2_05_0, db2_05_1, db2_05_2, db2_05_3, db2_05_4,
  db2_06_0, db2_06_1, db2_06_2, db2_06_3, db2_06_4,
  db2_07_0, db2_07_1, db2_07_2, db2_07_3, db2_07_4,
  db2_08_0, db2_08_1, db2_08_2, db2_08_3, db2_08_4,
  db2_09_0, db2_09_1, db2_09_2, db2_09_3, db2_09_4,
  db2_10_0, db2_10_1, db2_10_2, db2_10_3, db2_10_4,
  db2_11_0, db2_11_1, db2_11_2, db2_11_3, db2_11_4,
  db2_12_0, db2_12_1, db2_12_2, db2_12_3, db2_12_4,
  db2_13_0, db2_13_1, db2_13_2, db2_13_3, db2_13_4,
  db2_14_0, db2_14_1, db2_14_2, db2_14_3, db2_14_4,
  db2_15_0, db2_15_1, db2_15_2, db2_15_3, db2_15_4,
  db2_16_0, db2_16_1, db2_16_2, db2_16_3, db2_16_4,
  db2_17_0, db2_17_1, db2_17_2, db2_17_3, db2_17_4,
  db2_18_0, db2_18_1, db2_18_2, db2_18_3, db2_18_4,
  db2_19_0, db2_19_1, db2_19_2, db2_19_3, db2_19_4,
  db2_20_0, db2_20_1, db2_20_2, db2_20_3, db2_20_4,
  db2_21_0, db2_21_1, db2_21_2, db2_21_3, db2_21_4,
  db2_22_0, db2_22_1, db2_22_2, db2_22_3, db2_22_4,
  db2_23_0, db2_23_1, db2_23_2, db2_23_3, db2_23_4,
  db2_24_0, db2_24_1, db2_24_2, db2_24_3, db2_24_4,
  db2_25_0, db2_25_1, db2_25_2, db2_25_3, db2_25_4,
  db2_26_0, db2_26_1, db2_26_2, db2_26_3, db2_26_4,
  db2_27_0, db2_27_1, db2_27_2, db2_27_3, db2_27_4,
  db2_28_0, db2_28_1, db2_28_2, db2_28_3, db2_28_4,
  db2_29_0, db2_29_1, db2_29_2, db2_29_3, db2_29_4,
};

